# Generated by Django 5.0.1 on 2024-01-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
